# Generated by Django 5.2.4 on 2025-07-07 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Asta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('immagine', models.ImageField(upload_to='aste_images/')),
                ('prezzo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rilancio_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inizio', models.DateTimeField(auto_now_add=True)),
                ('data_fine', models.DateTimeField()),
                ('stato', models.CharField(choices=[('attiva', 'Attiva'), ('conclusa', 'Conclusa'), ('annullata', 'Annullata')], default='attiva', max_length=10)),
                ('utenti_lista_desideri', models.ManyToManyField(blank=True, related_name='lista_desideri', to=settings.AUTH_USER_MODEL)),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aste_create', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aste.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.PositiveIntegerField()),
                ('commento', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('asta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='aste.asta')),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_dati', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_ricevuti', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(choices=[('acquirente', 'Acquirente'), ('venditore', 'Venditore')], default='acquirente', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_offerta', models.DateTimeField(auto_now_add=True)),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte_fatte', to=settings.AUTH_USER_MODEL)),
                ('asta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to='aste.asta')),
            ],
            options={
                'ordering': ['-importo'],
                'unique_together': {('asta', 'importo')},
            },
        ),
    ]
