# Generated by Django 5.2.4 on 2025-07-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aste', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asta',
            options={'verbose_name_plural': 'Aste'},
        ),
        migrations.AlterModelOptions(
            name='offerta',
            options={'ordering': ['-importo'], 'verbose_name_plural': 'Offerte'},
        ),
    ]
