# Generated by Django 3.2 on 2025-07-14 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aste', '0002_alter_asta_options_alter_offerta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='asta',
            name='notifica_inviata',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaggio', models.TextField()),
                ('letta', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('asta_riferimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aste.asta')),
                ('utente_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_creazione'],
            },
        ),
    ]
