# Generated by Django 3.2 on 2025-07-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aste', '0003_auto_20250714_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asta',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='aste.categoria'),
            preserve_default=False,
        ),
    ]
